apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: foldify-open-ingress
    annotations:
        spec.ingressClassName: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
    tls:
        - hosts:
              - "your.domain.com"  # change this to your domain
          secretName: foldify-open-tls # change this to your TLS secret name
    rules:
        - host: "your.domain.com" # change this to your domain
          http:
              paths:
                  - path: /api/flask
                    pathType: Prefix
                    backend:
                        service:
                            name: flask-service
                            port:
                                number: 8080
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: nextjs-service
                            port:
                                number: 3000
